-- Add priority column to interview_questions table
ALTER TABLE interview_questions
ADD COLUMN IF NOT EXISTS priority TEXT CHECK (priority IN ('very_high', 'high', 'medium', 'low')) DEFAULT 'medium';

-- Update existing questions with priority
UPDATE interview_questions SET priority = 'very_high' WHERE is_featured = true;
UPDATE interview_questions SET priority = 'high' WHERE is_featured = false AND type = 'technical';
UPDATE interview_questions SET priority = 'medium' WHERE priority IS NULL;

-- Clear existing sample data to add new comprehensive set
DELETE FROM interview_questions;

-- Insert comprehensive question set with priority levels

-- GOOGLE - Software Engineer (System Design & Technical)
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Google', 'Software Engineer', 'technical', 'Design a web crawler like Googlebot', 'Key components: 1) URL frontier (queue), 2) HTML fetcher, 3) DNS resolver, 4) Content parser, 5) Duplicate detector (bloom filter/hash), 6) URL extractor, 7) Politeness module. Discuss distributed crawling, robots.txt compliance, and handling billions of URLs.', ARRAY['Discuss URL frontier data structure', 'Handle politeness (rate limiting)', 'Deduplication strategy', 'Distributed architecture', 'Handle failures and retries'], 'hard', 'very_high', ARRAY['system design', 'distributed systems', 'scalability'], true),

  ('Google', 'Software Engineer', 'technical', 'Design Google Maps / Navigation System', 'Components: 1) Graph representation (nodes=intersections, edges=roads), 2) Dijkstra/A* for shortest path, 3) Real-time traffic data integration, 4) ETA calculation, 5) Map tile serving, 6) Geo-indexing (quadtree/geohash). Discuss handling billions of queries, map updates, and offline mode.', ARRAY['Use A* for efficient pathfinding', 'Discuss preprocessing (contraction hierarchies)', 'Handle real-time traffic updates', 'Consider mobile data constraints', 'Discuss caching strategy'], 'hard', 'very_high', ARRAY['system design', 'algorithms', 'graphs', 'distributed systems'], true),

  ('Google', 'Software Engineer', 'technical', 'Design YouTube video streaming system', 'Architecture: 1) Video upload + transcoding pipeline, 2) CDN for global distribution, 3) Adaptive bitrate streaming (HLS/DASH), 4) Recommendation system, 5) View count aggregation, 6) Comment system. Discuss handling petabytes of video, global scale, and low latency playback.', ARRAY['Use CDN for video delivery', 'Discuss transcoding at scale', 'Handle concurrent viewers', 'Implement adaptive streaming', 'Design for 99.9% availability'], 'hard', 'very_high', ARRAY['system design', 'video streaming', 'CDN', 'scalability'], true),

  ('Google', 'Software Engineer', 'behavioral', 'Tell me about a time you had to work with a difficult team member', 'Use STAR method: Describe situation with teammate who disagreed on technical approach. Explain your task to find consensus. Detail actions - scheduled 1:1, listened to concerns, proposed POC of both approaches, measured objectively. Result - chose best solution together, strengthened working relationship.', ARRAY['Use STAR framework', 'Focus on collaboration', 'Show empathy and active listening', 'Demonstrate conflict resolution', 'End with positive outcome'], 'medium', 'very_high', ARRAY['teamwork', 'conflict resolution', 'communication'], true),

  ('Google', 'Software Engineer', 'behavioral', 'Why Google?', 'Research-specific reasons: Mention specific Google products/technologies you admire, Google''s engineering culture (20% time, focus on moonshots), impact at scale (billions of users), learning opportunities from world-class engineers, specific teams/projects you''re interested in.', ARRAY['Research specific teams and projects', 'Mention Google technologies you use/admire', 'Discuss engineering culture alignment', 'Show genuine enthusiasm', 'Avoid generic answers'], 'medium', 'very_high', ARRAY['motivation', 'company culture', 'career goals'], true),

  ('Google', 'Software Engineer', 'technical', 'Design a distributed cache system like Memcached', 'Design: 1) Consistent hashing for sharding, 2) LRU eviction policy, 3) Replication for availability, 4) Read-through/write-through strategies, 5) Expiration handling. Discuss cache invalidation, hot keys, and handling node failures.', ARRAY['Use consistent hashing', 'Implement LRU eviction', 'Handle cache stampede', 'Design for high availability', 'Discuss monitoring and metrics'], 'hard', 'high', ARRAY['system design', 'distributed systems', 'caching'], false),

-- META/FACEBOOK - Software Engineer
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Meta', 'Software Engineer', 'technical', 'Design Instagram feed ranking system', 'Components: 1) User interaction tracking (likes, comments, shares), 2) ML model for ranking (engagement prediction), 3) Feature extraction pipeline, 4) Real-time scoring service, 5) A/B testing framework. Discuss personalization, handling billions of posts, and balancing freshness vs relevance.', ARRAY['Discuss ML model features (recency, engagement, user affinity)', 'Handle real-time updates', 'Design for personalization', 'Consider feed diversity', 'Discuss A/B testing infrastructure'], 'hard', 'very_high', ARRAY['system design', 'machine learning', 'recommendation'], true),

  ('Meta', 'Software Engineer', 'technical', 'Design Facebook Messenger / WhatsApp', 'Architecture: 1) WebSocket connections for real-time messaging, 2) Message queue system, 3) Delivery receipts tracking, 4) End-to-end encryption, 5) Media storage, 6) Group chat handling. Discuss offline messages, message ordering, and handling billions of concurrent users.', ARRAY['Use WebSockets for real-time', 'Implement message queue', 'Handle offline scenarios', 'Design for E2E encryption', 'Ensure message ordering'], 'hard', 'very_high', ARRAY['system design', 'real-time systems', 'messaging'], true),

  ('Meta', 'Software Engineer', 'behavioral', 'Tell me about a time you failed', 'Use STAR: Describe specific failure (e.g., missed deadline, production bug). Explain what went wrong and why. Detail what you learned and how you changed your approach. Show growth - how you applied lessons to prevent similar issues. Demonstrate ownership and accountability.', ARRAY['Choose real, meaningful failure', 'Take ownership, no blame', 'Focus on learnings', 'Show how you grew', 'Keep it professional'], 'medium', 'very_high', ARRAY['growth mindset', 'self-awareness', 'learning'], true),

-- AMAZON - Software Engineer
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Amazon', 'Software Engineer', 'technical', 'Design Amazon product recommendation system', 'Architecture: 1) User behavior tracking (views, purchases, cart adds), 2) Collaborative filtering + content-based filtering, 3) Real-time recommendation service, 4) Offline batch processing for model training, 5) A/B testing. Discuss cold start problem, data pipeline, and personalization at scale.', ARRAY['Combine collaborative and content filtering', 'Handle cold start problem', 'Design real-time serving layer', 'Discuss data pipeline architecture', 'Implement A/B testing'], 'hard', 'very_high', ARRAY['system design', 'machine learning', 'recommendation', 'big data'], true),

  ('Amazon', 'Software Engineer', 'behavioral', 'Tell me about a time you had to learn something quickly', 'STAR format: Describe situation requiring new skill/technology. Explain the urgency and stakes. Detail your learning approach - broke down problem, found resources, built POC, asked for help when stuck. Result - delivered on time with new skill. Tie to Amazon''s "Learn and Be Curious" principle.', ARRAY['Show resourcefulness', 'Demonstrate learning strategy', 'Tie to Amazon Leadership Principles', 'Quantify the timeline', 'Show impact of what you learned'], 'medium', 'very_high', ARRAY['learning', 'adaptability', 'growth'], true),

-- MICROSOFT - Software Engineer
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Microsoft', 'Software Engineer', 'technical', 'Design OneDrive file sync system', 'Components: 1) File change detection (inotify/file watcher), 2) Chunking for large files, 3) Delta sync algorithm, 4) Conflict resolution, 5) Version history, 6) Shared folder permissions. Discuss handling large files, offline sync, and cross-device consistency.', ARRAY['Use chunking for large files', 'Implement delta sync', 'Handle conflict resolution', 'Design for offline mode', 'Ensure eventual consistency'], 'hard', 'very_high', ARRAY['system design', 'file systems', 'distributed systems'], true),

-- NETFLIX - Software Engineer
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Netflix', 'Software Engineer', 'technical', 'Design Netflix video recommendation engine', 'System: 1) User viewing history tracking, 2) Collaborative filtering (user-user, item-item), 3) Content features (genre, actors, metadata), 4) Deep learning models, 5) Real-time personalization, 6) A/B testing infrastructure. Discuss cold start, scalability to 200M+ users, and balancing exploration/exploitation.', ARRAY['Use hybrid recommendation approach', 'Handle cold start with content features', 'Design for real-time updates', 'Implement multi-armed bandit for exploration', 'Discuss offline vs online metrics'], 'hard', 'high', ARRAY['system design', 'ML', 'recommendation', 'personalization'], false),

-- GOLDMAN SACHS - Investment Banking
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Goldman Sachs', 'Investment Banking Analyst', 'technical', 'Walk me through a DCF valuation', 'DCF process: 1) Project unlevered free cash flows (5-10 years) using revenue growth, margins, CapEx, NWC changes. 2) Calculate terminal value using perpetuity growth or exit multiple. 3) Determine WACC (cost of equity via CAPM, cost of debt, capital structure). 4) Discount all cash flows to PV. 5) Sum to get enterprise value, subtract net debt for equity value.', ARRAY['Know FCF formula by heart', 'Understand WACC components deeply', 'Be ready to walk through example', 'Discuss sensitivity analysis', 'Defend your assumptions'], 'hard', 'very_high', ARRAY['valuation', 'DCF', 'finance', 'modeling'], true),

  ('Goldman Sachs', 'Investment Banking Analyst', 'technical', 'How would you value a company?', 'Three main approaches: 1) DCF (intrinsic value based on cash flows), 2) Comparable companies analysis (trading multiples like EV/EBITDA, P/E), 3) Precedent transactions (M&A multiples). Typically use all three to triangulate value. Discuss pros/cons of each method.', ARRAY['Know all three valuation methods', 'Discuss when to use each', 'Mention triangulation approach', 'Be ready to go deep on DCF', 'Understand multiples selection'], 'medium', 'very_high', ARRAY['valuation', 'finance', 'M&A'], true),

  ('Goldman Sachs', 'Investment Banking Analyst', 'behavioral', 'Walk me through your resume', 'Structure: 1) Brief background (school, major), 2) Chronologically cover each experience with specific deals/projects, quantifiable impact, skills developed, 3) Connect experiences to show progression toward IB, 4) Conclude with why you''re interested in Goldman now. Keep to 90 seconds.', ARRAY['Practice to 90 seconds max', 'Emphasize deals/transactions', 'Quantify your impact', 'Show clear interest in finance', 'End with why Goldman'], 'medium', 'very_high', ARRAY['resume', 'personal pitch', 'communication'], true),

-- MCKINSEY - Consultant
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('McKinsey', 'Consultant', 'case_study', 'A retail client is experiencing declining profits. How would you approach this?', 'Framework: 1) Clarify (timeframe, geography, product lines, definition of profit), 2) Structure using profitability tree (Profit = Revenue - Costs), 3) Hypothesize root causes, 4) Analyze each branch (Revenue: price vs volume; Costs: fixed vs variable), 5) Quantify impact, 6) Develop recommendations with implementation roadmap.', ARRAY['Start with clarifying questions', 'Use structured framework (profit tree)', 'Develop hypothesis early', 'Quantify everything', 'Provide actionable recommendations', 'Consider implementation challenges'], 'hard', 'very_high', ARRAY['case interview', 'profitability', 'framework', 'business strategy'], true),

  ('McKinsey', 'Consultant', 'case_study', 'Should our client enter the electric vehicle market?', 'Framework: 1) Market attractiveness (size, growth, profitability, competition), 2) Client capabilities (technology, capital, brand, distribution), 3) Financial analysis (investment required, ROI, NPV), 4) Risks and mitigation (regulatory, technological, competitive). Recommendation with clear rationale and next steps.', ARRAY['Use market entry framework', 'Start with market sizing', 'Assess competitive landscape', 'Evaluate client strengths/weaknesses', 'Quantify financials', 'Address key risks'], 'hard', 'very_high', ARRAY['case interview', 'market entry', 'strategy'], true),

  ('McKinsey', 'Consultant', 'behavioral', 'Why consulting? Why McKinsey?', 'Structure: 1) Why consulting: Problem-solving, steep learning curve, exposure to industries/functions, client impact. 2) Why McKinsey: Global reach, culture of excellence, alumni network, specific practice areas of interest (e.g., digital, operations). Provide specific examples and show genuine research.', ARRAY['Show genuine interest in problem-solving', 'Reference specific McKinsey work/publications', 'Mention practice areas you researched', 'Discuss culture fit', 'Avoid generic answers'], 'medium', 'very_high', ARRAY['motivation', 'career goals', 'firm culture'], true),

-- BCG - Consultant
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('BCG', 'Consultant', 'case_study', 'A pharmaceutical company wants to increase profits. What would you recommend?', 'Framework: 1) Clarify scope (specific drugs? timeframe? markets?), 2) Structure (Profit = Revenue - Cost), 3) Revenue options (pricing, volume, new products, new markets), 4) Cost options (R&D efficiency, manufacturing, SG&A), 5) Analyze pipeline, patent cliff, regulatory. Provide prioritized recommendations.', ARRAY['Clarify the scope immediately', 'Consider pharma-specific factors (patents, FDA)', 'Discuss R&D pipeline', 'Analyze pricing power', 'Consider regulatory constraints'], 'hard', 'high', ARRAY['case interview', 'profitability', 'pharma'], false),

-- APPLE - Software Engineer
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Apple', 'Software Engineer', 'technical', 'Design iCloud photo sync system', 'Design: 1) Device photo detection, 2) Image upload with deduplication (perceptual hashing), 3) Server-side storage with compression, 4) Thumbnail generation, 5) Cross-device sync, 6) Sharing and albums. Discuss privacy (E2E encryption), bandwidth optimization, and handling billions of photos.', ARRAY['Emphasize privacy and encryption', 'Use perceptual hashing for deduplication', 'Optimize for mobile bandwidth', 'Handle varying image qualities', 'Discuss iCloud storage tiers'], 'hard', 'high', ARRAY['system design', 'cloud storage', 'privacy'], false),

-- More questions for variety
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Amazon', 'Software Engineer', 'behavioral', 'Tell me about a time you went above and beyond', 'STAR: Describe situation where baseline wasn''t enough. Explain extra initiative you took beyond requirements. Detail specific actions - extra research, proactive improvements, helping team members. Quantify the impact. Tie to "Deliver Results" and "Ownership" principles.', ARRAY['Show initiative', 'Quantify impact', 'Tie to Amazon Leadership Principles', 'Demonstrate ownership', 'Show how it benefited others/company'], 'medium', 'high', ARRAY['initiative', 'leadership', 'impact'], false),

  ('Google', 'Software Engineer', 'technical', 'Design rate limiter / API throttling system', 'Design: 1) Token bucket or sliding window algorithm, 2) Distributed rate limiting (Redis), 3) Rate limit rules (per user, per IP, per API key), 4) Graceful degradation, 5) Monitoring and alerts. Discuss handling distributed systems challenges and consistency.', ARRAY['Compare token bucket vs sliding window', 'Use Redis for distributed state', 'Handle race conditions', 'Provide clear error responses', 'Implement retry-after headers'], 'medium', 'high', ARRAY['system design', 'algorithms', 'distributed systems'], false),

  ('Meta', 'Product Manager', 'behavioral', 'How would you prioritize features for Instagram Stories?', 'Framework: 1) Clarify goals (engagement, retention, revenue, growth), 2) Identify user segments and needs, 3) Score features using Impact vs Effort matrix or RICE, 4) Consider technical constraints and dependencies, 5) Create roadmap with rationale. Discuss A/B testing and metrics.', ARRAY['Start with goals and metrics', 'Use prioritization framework (RICE/ICE)', 'Consider multiple stakeholders', 'Discuss trade-offs explicitly', 'Mention A/B testing', 'Talk about success metrics'], 'medium', 'very_high', ARRAY['product strategy', 'prioritization', 'frameworks'], true),

  ('JPMorgan', 'Investment Banking Analyst', 'technical', 'What are the three financial statements and how do they link?', 'Three statements: 1) Income Statement (revenue, expenses, net income), 2) Balance Sheet (assets, liabilities, equity), 3) Cash Flow Statement (operating, investing, financing). Links: Net income flows to CFS and retained earnings. Changes in BS items flow to CFS. Depreciation in IS and CFS. CapEx in CFS and BS.', ARRAY['Draw the linkages diagram', 'Know all connections', 'Walk through an example', 'Explain depreciation flow', 'Discuss working capital changes'], 'medium', 'very_high', ARRAY['accounting', 'financial statements', 'finance'], true),

  ('Microsoft', 'Software Engineer', 'behavioral', 'Describe a time when you had to make a decision with incomplete information', 'STAR: Situation requiring decision without full data. Explain the stakes and constraints. Detail approach - gathered available data, consulted experts, made assumptions, created decision framework, mitigated risks. Result and lessons learned. Show decisiveness and risk management.', ARRAY['Show analytical thinking', 'Explain your decision framework', 'Discuss risk mitigation', 'Demonstrate confidence in uncertainty', 'Reflect on outcome'], 'medium', 'high', ARRAY['decision making', 'judgment', 'leadership'], false),

  ('Bain', 'Consultant', 'case_study', 'How many gas stations are there in the United States?', 'Framework (Market Sizing): 1) Population: 330M people, 2) Cars: ~250M cars (assuming 1.3 people per car), 3) Gas fill-ups: once per week on average, 4) Station capacity: ~200 cars/day, 5) Calculate: (250M * 52/200)/365 ≈ 180K stations. Sanity check and refine assumptions.', ARRAY['State all assumptions clearly', 'Round numbers for easier math', 'Build from bottom-up or top-down', 'Sense-check your answer', 'Show structured thinking'], 'medium', 'high', ARRAY['market sizing', 'estimation', 'quantitative'], false);
