-- Add 100+ more comprehensive interview questions across all roles

-- SOFTWARE ENGINEER - Additional questions (40+ more)

-- Facebook/Meta
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Meta', 'Software Engineer', 'technical', 'Design a notification system for Facebook', 'Components: 1) Event producers (posts, comments, likes), 2) Message queue (Kafka), 3) Notification service (filtering, preferences), 4) Delivery channels (push, email, in-app), 5) User preferences service, 6) Rate limiting. Discuss fan-out strategies, handling billions of events, and real-time delivery.', ARRAY['Use message queue for scalability', 'Implement user preferences', 'Discuss fan-out on write vs read', 'Handle rate limiting', 'Consider mobile push delivery'], 'hard', 'very_high', ARRAY['system design', 'distributed systems', 'notifications'], true),

  ('Meta', 'Software Engineer', 'technical', 'Implement a function to detect cycle in a linked list', 'Use Floyd''s cycle detection (tortoise and hare). Two pointers: slow moves 1 step, fast moves 2 steps. If they meet, cycle exists. Time: O(n), Space: O(1). Return meeting point or null.', ARRAY['Use two pointers', 'Explain Floyd''s algorithm', 'Handle edge cases (empty list)', 'Discuss time/space complexity', 'Find cycle start if needed'], 'medium', 'high', ARRAY['algorithms', 'linked-list', 'two-pointers'], false),

  ('Meta', 'Software Engineer', 'behavioral', 'Tell me about a time you had to deal with conflicting priorities', 'STAR: Describe situation with multiple urgent requests. Explain how you assessed impact and urgency, communicated with stakeholders, negotiated deadlines, and made data-driven decisions. Show outcome and how you maintained relationships.', ARRAY['Show prioritization framework', 'Emphasize communication', 'Demonstrate stakeholder management', 'Quantify impact of decision', 'Show empathy'], 'medium', 'high', ARRAY['prioritization', 'stakeholder-management', 'communication'], false);

-- Google
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Google', 'Software Engineer', 'technical', 'Design Google Drive file sharing and permissions', 'Design: 1) File metadata service, 2) Permission service (user, group, public), 3) Access control lists (ACLs), 4) Inheritance model, 5) Share link generation, 6) Audit logging. Discuss permission propagation, revocation, and handling millions of shares.', ARRAY['Design ACL system', 'Handle permission inheritance', 'Discuss share links with expiry', 'Implement audit logs', 'Consider permission caching'], 'hard', 'very_high', ARRAY['system design', 'access-control', 'security'], true),

  ('Google', 'Software Engineer', 'technical', 'Find all anagrams in a string', 'Use sliding window with character frequency map. Maintain window of pattern length, compare frequency maps. Time: O(n), Space: O(1) (26 letters). Return starting indices of anagrams.', ARRAY['Sliding window approach', 'Use frequency map', 'Optimize comparisons', 'Handle edge cases', 'Explain time complexity'], 'medium', 'high', ARRAY['algorithms', 'sliding-window', 'strings', 'hash-map'], false),

  ('Google', 'Software Engineer', 'technical', 'Design Google Calendar', 'Components: 1) Event service (CRUD), 2) Recurrence engine, 3) Reminder service, 4) Availability/scheduling service, 5) Timezone handling, 6) Sync service (mobile, web), 7) Invitation system. Discuss conflict detection, recurrence patterns, and cross-timezone scheduling.', ARRAY['Handle recurring events (RRULE)', 'Implement conflict detection', 'Discuss timezone complexity', 'Design sync mechanism', 'Handle invitations/RSVP'], 'hard', 'very_high', ARRAY['system design', 'calendar', 'distributed systems'], true),

  ('Google', 'Software Engineer', 'behavioral', 'Describe a time you improved a process or system', 'STAR: Identify inefficiency in existing process. Explain analysis, proposed solution, how you gained buy-in, implementation, and measured impact. Show initiative and data-driven approach.', ARRAY['Quantify the improvement', 'Show data analysis', 'Demonstrate initiative', 'Explain change management', 'Measure impact with metrics'], 'medium', 'high', ARRAY['initiative', 'process-improvement', 'impact'], false),

  ('Google', 'Software Engineer', 'technical', 'Implement an autocomplete system', 'Use Trie data structure. Store words with frequencies. For prefix search, traverse trie to prefix node, then DFS/BFS to find top-k completions. Optimize with caching popular prefixes. Time: O(p + k log k), Space: O(n*m) for trie.', ARRAY['Use Trie data structure', 'Implement top-k retrieval', 'Discuss caching strategy', 'Handle ranking/scoring', 'Optimize for scale'], 'medium', 'high', ARRAY['data-structures', 'trie', 'algorithms'], false);

-- Amazon
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Amazon', 'Software Engineer', 'technical', 'Design Amazon shopping cart', 'Components: 1) Cart service (add/remove/update), 2) Session management, 3) Inventory service integration, 4) Price calculation service, 5) Persistence (DB + cache), 6) Cart sync across devices. Discuss handling race conditions, abandoned carts, and session management.', ARRAY['Handle concurrent updates', 'Design session management', 'Discuss cart persistence', 'Implement price recalculation', 'Handle inventory checks'], 'hard', 'very_high', ARRAY['system design', 'e-commerce', 'distributed systems'], true),

  ('Amazon', 'Software Engineer', 'behavioral', 'Tell me about a time you missed a deadline', 'STAR: Describe situation where deadline was missed. Take ownership, explain what went wrong, how you communicated early, mitigation steps taken, and most importantly - what you learned and changed. Tie to "Deliver Results".', ARRAY['Take full ownership', 'Show early communication', 'Focus on learnings', 'Explain process changes', 'Demonstrate growth'], 'medium', 'high', ARRAY['ownership', 'accountability', 'learning'], false),

  ('Amazon', 'Software Engineer', 'technical', 'Merge K sorted lists', 'Use min-heap. Add first element of each list to heap. Pop minimum, add next element from that list. Continue until heap empty. Time: O(N log k) where N = total elements, k = number of lists. Space: O(k) for heap.', ARRAY['Use min-heap approach', 'Explain heap operations', 'Handle edge cases (empty lists)', 'Discuss time/space complexity', 'Consider divide and conquer alternative'], 'medium', 'high', ARRAY['algorithms', 'heap', 'linked-list'], false),

  ('Amazon', 'Software Engineer', 'technical', 'Design Amazon order tracking system', 'Components: 1) Order service, 2) Tracking events (ordered, shipped, in-transit, delivered), 3) Event sourcing pattern, 4) Notification service, 5) Carrier integration, 6) Real-time updates. Discuss event-driven architecture, handling delays, and notification strategy.', ARRAY['Use event sourcing', 'Design state machine for order status', 'Integrate with carriers (APIs)', 'Implement real-time notifications', 'Handle exceptions/delays'], 'hard', 'high', ARRAY['system design', 'event-driven', 'e-commerce'], false),

  ('Amazon', 'Software Engineer', 'behavioral', 'Give an example of when you took a calculated risk', 'STAR: Describe risky technical decision. Explain analysis of pros/cons, risk mitigation steps, stakeholder communication, execution, and outcome. Show "Bias for Action" while being thoughtful.', ARRAY['Show analytical thinking', 'Explain risk assessment', 'Demonstrate bias for action', 'Discuss mitigation plan', 'Quantify outcome'], 'medium', 'high', ARRAY['decision-making', 'risk-management', 'leadership'], false);

-- Microsoft
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Microsoft', 'Software Engineer', 'technical', 'Design Microsoft Teams chat system', 'Architecture: 1) WebSocket for real-time messaging, 2) Message service (send/receive), 3) Channel/group management, 4) Thread/reply support, 5) File sharing integration, 6) Search service, 7) Presence service. Discuss handling message ordering, delivery guarantees, and scalability.', ARRAY['Use WebSockets for real-time', 'Implement message ordering', 'Design channel permissions', 'Handle file attachments', 'Discuss presence system'], 'hard', 'very_high', ARRAY['system design', 'messaging', 'real-time'], true),

  ('Microsoft', 'Software Engineer', 'technical', 'Reverse a linked list', 'Iterative: Use three pointers (prev, current, next). Reverse links as you traverse. Time: O(n), Space: O(1). Recursive: Reverse rest of list, fix pointers. Time: O(n), Space: O(n) stack.', ARRAY['Show iterative solution', 'Explain pointer manipulation', 'Discuss recursive approach', 'Handle edge cases', 'Compare space complexity'], 'easy', 'high', ARRAY['algorithms', 'linked-list'], false),

  ('Microsoft', 'Software Engineer', 'behavioral', 'How do you handle feedback or criticism?', 'Describe specific example of receiving tough feedback. Show active listening, lack of defensiveness, reflection on feedback, action taken to improve, and follow-up. Demonstrate growth mindset.', ARRAY['Show openness to feedback', 'Demonstrate self-awareness', 'Explain action taken', 'Show growth mindset', 'Discuss outcome'], 'medium', 'high', ARRAY['feedback', 'growth-mindset', 'communication'], false),

  ('Microsoft', 'Software Engineer', 'technical', 'Design Excel auto-save and collaboration', 'Components: 1) Operational Transformation (OT) or CRDT for concurrent edits, 2) Change tracking, 3) Auto-save service (debounced), 4) Conflict resolution, 5) Version history, 6) WebSocket for real-time sync. Discuss handling conflicts and ensuring consistency.', ARRAY['Use OT or CRDT for collab', 'Implement conflict resolution', 'Design auto-save with debouncing', 'Handle version history', 'Discuss real-time sync'], 'hard', 'very_high', ARRAY['system design', 'collaboration', 'distributed systems'], true),

  ('Microsoft', 'Software Engineer', 'technical', 'Valid parentheses problem', 'Use stack. Push opening brackets, pop when closing bracket matches. If mismatch or stack not empty at end, invalid. Time: O(n), Space: O(n). Extend for multiple types: (), [], {}.', ARRAY['Use stack data structure', 'Handle all bracket types', 'Check edge cases', 'Explain time/space complexity', 'Show clean implementation'], 'easy', 'medium', ARRAY['algorithms', 'stack', 'strings'], false);

-- Apple
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Apple', 'Software Engineer', 'technical', 'Design Find My iPhone location tracking', 'Components: 1) Location service (GPS, WiFi triangulation), 2) Device registration, 3) Location update service (periodic), 4) Map visualization, 5) Privacy/encryption, 6) Offline location (BLE mesh), 7) Lost mode triggers. Discuss privacy, battery optimization, and offline tracking.', ARRAY['Emphasize privacy by design', 'Discuss battery optimization', 'Explain BLE mesh network', 'Handle offline scenarios', 'Implement location encryption'], 'hard', 'very_high', ARRAY['system design', 'location', 'privacy', 'mobile'], true),

  ('Apple', 'Software Engineer', 'behavioral', 'Why Apple?', 'Research-driven answer: Mention specific products you love, Apple''s focus on user experience and design, privacy-first approach, ecosystem integration, innovation in hardware/software, specific teams/projects. Show genuine passion.', ARRAY['Reference specific Apple products', 'Discuss design/UX philosophy', 'Mention privacy commitment', 'Show ecosystem understanding', 'Be authentic'], 'medium', 'high', ARRAY['motivation', 'company-culture'], false),

  ('Apple', 'Software Engineer', 'technical', 'Two sum problem', 'Use hash map to store complements. For each element, check if complement exists. If yes, return indices. If no, store element. Time: O(n), Space: O(n). Handle duplicates and edge cases.', ARRAY['Use hash map approach', 'Handle duplicates', 'Explain time/space trade-off', 'Check edge cases', 'One-pass solution'], 'easy', 'medium', ARRAY['algorithms', 'hash-map', 'arrays'], false),

  ('Apple', 'Software Engineer', 'technical', 'Design FaceTime video calling', 'Architecture: 1) Signaling server (WebRTC), 2) STUN/TURN servers for NAT traversal, 3) Media servers for group calls, 4) Encryption (E2E), 5) Quality adaptation, 6) Connection fallback, 7) Cross-platform support. Discuss peer-to-peer vs server-mediated, quality adaptation, and handling network issues.', ARRAY['Use WebRTC for video', 'Explain STUN/TURN for NAT', 'Implement E2E encryption', 'Handle quality adaptation', 'Discuss group call architecture'], 'hard', 'very_high', ARRAY['system design', 'video', 'WebRTC', 'networking'], true);

-- Netflix
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Netflix', 'Software Engineer', 'technical', 'Design Netflix viewing history and resume playback', 'Components: 1) Playback position tracking, 2) Viewing history service, 3) Resume service (device sync), 4) Watch progress calculation, 5) Continue watching UI, 6) Event tracking. Discuss consistency across devices, handling concurrent streams, and data staleness.', ARRAY['Track playback position precisely', 'Sync across devices', 'Handle concurrent viewing', 'Design for eventual consistency', 'Implement progress calculation'], 'medium', 'high', ARRAY['system design', 'streaming', 'sync'], false),

  ('Netflix', 'Software Engineer', 'behavioral', 'Tell me about a time you had to make a tough technical decision', 'STAR: Describe decision between two valid technical approaches. Explain trade-offs analyzed, data gathered, stakeholders consulted, decision made, and outcome. Show technical judgment and decision-making process.', ARRAY['Explain trade-offs clearly', 'Show data-driven approach', 'Discuss stakeholder input', 'Demonstrate decisiveness', 'Reflect on outcome'], 'medium', 'high', ARRAY['decision-making', 'technical-leadership'], false);

-- Uber
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Uber', 'Software Engineer', 'technical', 'Design Uber surge pricing system', 'Components: 1) Demand calculation (rider requests), 2) Supply calculation (available drivers), 3) Pricing algorithm (supply/demand ratio), 4) Geo-fencing for zones, 5) Real-time price updates, 6) Notification service, 7) Historical data analysis. Discuss dynamic pricing, zone management, and real-time computation.', ARRAY['Calculate supply/demand ratio', 'Implement geo-fencing', 'Design pricing algorithm', 'Handle real-time updates', 'Consider fairness/caps'], 'hard', 'very_high', ARRAY['system design', 'dynamic-pricing', 'real-time'], true),

  ('Uber', 'Software Engineer', 'behavioral', 'Describe a time you had to work with ambiguous requirements', 'STAR: Project with unclear specs. Explain how you clarified scope, made assumptions, documented decisions, iterated with stakeholders, and delivered. Show comfort with ambiguity and ownership.', ARRAY['Show how you drove clarity', 'Demonstrate assumption documentation', 'Emphasize iteration', 'Show ownership', 'Discuss outcome'], 'medium', 'high', ARRAY['ambiguity', 'ownership', 'communication'], false);

-- Airbnb
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Airbnb', 'Software Engineer', 'technical', 'Design Airbnb search and filter system', 'Components: 1) Elasticsearch for search, 2) Filter service (price, dates, amenities, guests), 3) Availability service, 4) Ranking algorithm, 5) Geospatial search, 6) Caching layer. Discuss handling complex filters, availability calculation, and search performance.', ARRAY['Use Elasticsearch for search', 'Implement geospatial queries', 'Handle availability efficiently', 'Design ranking algorithm', 'Optimize for performance'], 'hard', 'very_high', ARRAY['system design', 'search', 'geospatial'], true),

  ('Airbnb', 'Software Engineer', 'technical', 'Clone a graph', 'Use DFS or BFS with hash map to track cloned nodes. For each node, clone it and its neighbors recursively. Handle cycles. Time: O(V+E), Space: O(V) for hash map.', ARRAY['Use DFS/BFS with hash map', 'Handle cycles correctly', 'Clone all edges', 'Explain time/space complexity', 'Discuss iterative vs recursive'], 'medium', 'high', ARRAY['algorithms', 'graph', 'DFS', 'hash-map'], false);

-- Stripe
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Stripe', 'Software Engineer', 'technical', 'Design Stripe refund system', 'Components: 1) Refund service (full/partial), 2) Payment gateway integration, 3) Transaction reversal, 4) Dispute handling, 5) Webhook notifications, 6) Reconciliation service, 7) Audit logging. Discuss idempotency, handling partial refunds, and financial consistency.', ARRAY['Ensure idempotency', 'Handle partial refunds', 'Implement audit logging', 'Design reconciliation', 'Consider dispute process'], 'hard', 'very_high', ARRAY['system design', 'payments', 'fintech'], true),

  ('Stripe', 'Software Engineer', 'behavioral', 'Tell me about a time you identified and fixed a critical bug', 'STAR: Critical production issue discovered. Explain debugging process, root cause analysis, fix implementation, verification, and prevention measures. Show technical depth and ownership.', ARRAY['Show systematic debugging', 'Explain root cause clearly', 'Discuss impact mitigation', 'Detail prevention measures', 'Show ownership'], 'medium', 'high', ARRAY['debugging', 'ownership', 'technical-excellence'], false);

-- LinkedIn
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('LinkedIn', 'Software Engineer', 'technical', 'Design LinkedIn connection suggestion system', 'Components: 1) Graph database (user connections), 2) Mutual connections calculation, 3) ML model for scoring, 4) Company/school affiliation, 5) Interaction history, 6) Ranking service, 7) Notification service. Discuss graph traversal, feature engineering, and personalization.', ARRAY['Use graph algorithms', 'Calculate mutual connections', 'Implement scoring model', 'Consider multiple signals', 'Optimize graph queries'], 'hard', 'very_high', ARRAY['system design', 'graph', 'ML', 'social-network'], true),

  ('LinkedIn', 'Software Engineer', 'technical', 'Longest palindromic substring', 'Expand around center approach. For each character, expand outward checking palindrome. Handle even/odd length. Time: O(n²), Space: O(1). Alternative: Dynamic programming O(n²) time and space.', ARRAY['Expand around center', 'Handle even/odd length', 'Optimize space', 'Discuss DP alternative', 'Explain time complexity'], 'medium', 'high', ARRAY['algorithms', 'strings', 'dynamic-programming'], false);

-- Twitter/X
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Twitter', 'Software Engineer', 'technical', 'Design Twitter timeline ranking', 'Components: 1) Tweet ingestion, 2) Fan-out service, 3) ML ranking model (engagement prediction), 4) Feature extraction, 5) Real-time scoring, 6) Timeline assembly, 7) A/B testing. Discuss fan-out strategies, ranking signals, and handling trending topics.', ARRAY['Choose fan-out strategy', 'Design ranking model', 'Handle real-time updates', 'Discuss personalization', 'Consider trending signals'], 'hard', 'very_high', ARRAY['system design', 'ML', 'ranking', 'social-media'], true),

  ('Twitter', 'Software Engineer', 'technical', 'Top K frequent elements', 'Use hash map for frequency count, then min-heap of size k or bucket sort. Heap: Time O(n log k), Space O(n). Bucket sort: Time O(n), Space O(n). Return top k elements.', ARRAY['Count frequencies with map', 'Use heap or bucket sort', 'Compare approaches', 'Explain time/space trade-offs', 'Handle ties'], 'medium', 'high', ARRAY['algorithms', 'heap', 'hash-map'], false);

-- Spotify
INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Spotify', 'Software Engineer', 'technical', 'Design Spotify playlist collaborative editing', 'Components: 1) Real-time sync (WebSocket), 2) Operational Transform or CRDT, 3) Conflict resolution, 4) Version history, 5) Permission management, 6) Change notifications. Discuss handling concurrent edits and ensuring consistency.', ARRAY['Use OT or CRDT', 'Handle concurrent edits', 'Implement conflict resolution', 'Design permissions', 'Real-time sync'], 'hard', 'high', ARRAY['system design', 'collaboration', 'real-time'], false);

-- PRODUCT MANAGER - Additional questions (20+ more)

INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Google', 'Product Manager', 'behavioral', 'How would you improve YouTube to increase watch time?', 'Framework: 1) Clarify goal (overall watch time vs session time), 2) Segment users (casual vs power users), 3) Pain points (content discovery, quality, interruptions), 4) Solutions (better recommendations, autoplay optimization, content quality, watch later improvements), 5) Metrics (avg session time, retention, DAU). Prioritize using impact/effort.', ARRAY['Define the metric clearly', 'Segment users', 'Use data to identify pain points', 'Prioritize solutions', 'Tie to business goals'], 'hard', 'very_high', ARRAY['product-improvement', 'metrics', 'video'], true),

  ('Amazon', 'Product Manager', 'behavioral', 'Design a product for elderly users', 'Process: 1) Understand needs (accessibility, simplicity, trust), 2) Research pain points (technology barriers, physical limitations), 3) Design solutions (large buttons, voice interface, family sharing, emergency features), 4) Go-to-market (partnerships with senior centers), 5) Metrics (adoption, engagement, satisfaction). Show user empathy.', ARRAY['Deep user research', 'Focus on accessibility', 'Simple design principles', 'Build trust/safety', 'Define success metrics'], 'hard', 'very_high', ARRAY['product-design', 'accessibility', 'user-research'], true),

  ('Apple', 'Product Manager', 'behavioral', 'How would you prioritize features for the next iPhone?', 'Framework: 1) Understand strategy (market position, competition), 2) User needs (battery, camera, performance, new capabilities), 3) Technical feasibility, 4) Competitive analysis, 5) Business impact (ASP, differentiation), 6) Roadmap (what ships when). Use value vs effort matrix. Consider ecosystem.', ARRAY['Align with Apple strategy', 'Balance innovation and reliability', 'Consider ecosystem integration', 'Discuss trade-offs', 'Quantify business impact'], 'hard', 'very_high', ARRAY['prioritization', 'hardware-product', 'strategy'], true),

  ('Spotify', 'Product Manager', 'case_study', 'Spotify premium subscriptions dropped 10%. Investigate.', 'Framework: 1) Clarify (timeframe, geography, plan type), 2) Hypotheses (pricing changes, competition, churn, payment failures, feature changes), 3) Data analysis (cohort analysis, cancellation reasons, competitive intel), 4) Root cause, 5) Solutions (win-back campaigns, pricing tests, feature improvements), 6) Prioritize and measure.', ARRAY['Segment the problem', 'Form data-driven hypotheses', 'Analyze cancellation funnel', 'Consider external factors', 'Propose actionable solutions'], 'hard', 'very_high', ARRAY['root-cause-analysis', 'subscriptions', 'metrics'], true),

  ('Google', 'Product Manager', 'behavioral', 'How would you measure success for Google Search?', 'Multi-level metrics: 1) User satisfaction (query success rate, time to answer, bounce rate, SERP CTR), 2) Engagement (searches per user, DAU), 3) Business (revenue per search, ad clicks), 4) Quality (zero-click searches for quick answers). Discuss trade-offs and leading vs lagging indicators.', ARRAY['Define metric hierarchy', 'Balance user and business metrics', 'Discuss leading indicators', 'Consider quality metrics', 'Acknowledge trade-offs'], 'hard', 'high', ARRAY['metrics', 'measurement', 'search'], false),

  ('Netflix', 'Product Manager', 'behavioral', 'Should Netflix enter the gaming market?', 'Framework: 1) Market analysis (size, growth, competition), 2) Strategic fit (content ecosystem, engagement, retention), 3) User demand (surveys, gaming consumption), 4) Capabilities (licensing vs development, cloud gaming), 5) Financials (investment, ROI, cannibalization), 6) Risk (execution, brand dilution). Recommendation with rationale.', ARRAY['Assess strategic fit', 'Analyze market opportunity', 'Consider capabilities', 'Discuss build vs buy', 'Address key risks'], 'hard', 'very_high', ARRAY['strategy', 'market-entry', 'gaming'], true),

  ('Uber', 'Product Manager', 'behavioral', 'Design a feature to improve driver retention', 'Process: 1) Understand churn reasons (earnings, flexibility, support, safety), 2) Segment drivers (full-time vs part-time), 3) Solutions (earnings transparency, quest/incentives, better support, benefits, community features), 4) Test and iterate, 5) Metrics (retention rate, hours driven, satisfaction). Show empathy for drivers.', ARRAY['Research driver pain points', 'Segment driver types', 'Balance supply economics', 'Propose multiple solutions', 'Measure retention impact'], 'hard', 'high', ARRAY['product-design', 'retention', 'supply-side'], false),

  ('Airbnb', 'Product Manager', 'case_study', 'How would you increase bookings in a specific city?', 'Framework: 1) Understand current state (supply, demand, pricing, conversion), 2) Diagnose (supply shortage, quality issues, pricing, trust, awareness), 3) Solutions: Supply-side (recruit hosts, improve listings, pricing tools), Demand-side (marketing, partnerships, discounts, improved search/discovery), 4) Prioritize by impact, 5) Metrics (listings, occupancy, bookings).', ARRAY['Diagnose supply vs demand', 'Consider both sides of marketplace', 'Local market dynamics', 'Propose balanced solutions', 'Define clear metrics'], 'hard', 'very_high', ARRAY['marketplace', 'growth', 'city-ops'], true),

  ('Microsoft', 'Product Manager', 'behavioral', 'How do you work with engineering teams?', 'Best practices: 1) Clear PRDs with "why" not just "what", 2) Early involvement in design, 3) Regular communication, 4) Respect technical constraints, 5) Data-driven decisions, 6) Clear prioritization, 7) Celebrate wins together. Give specific examples of collaboration.', ARRAY['Show respect for engineering', 'Emphasize collaboration', 'Provide specific examples', 'Discuss trade-offs', 'Show data-driven approach'], 'medium', 'high', ARRAY['cross-functional', 'engineering-partnership'], false),

  ('Amazon', 'Product Manager', 'behavioral', 'Tell me about a product you launched that failed', 'STAR: Describe failed product launch. Explain what happened, why it failed (user research gaps, wrong assumptions, execution issues), how you responded, what you learned, and how you applied lessons to future work. Show ownership and growth.', ARRAY['Take full ownership', 'Analyze root cause', 'Show learnings', 'Demonstrate resilience', 'Apply to future work'], 'medium', 'high', ARRAY['failure', 'learning', 'ownership'], false),

  ('LinkedIn', 'Product Manager', 'behavioral', 'How would you grow LinkedIn Premium subscriptions?', 'Framework: 1) Understand current state (conversion rate, churn), 2) Target segments (job seekers, recruiters, sales professionals), 3) Value props (InMail, insights, learning), 4) Growth levers (free trial, feature gating, bundles, pricing tiers), 5) Acquisition and retention strategies, 6) Metrics (signups, LTV, retention). Prioritize by segment.', ARRAY['Segment users by value prop', 'Optimize conversion funnel', 'Balance acquisition and retention', 'Test pricing strategies', 'Measure LTV'], 'hard', 'very_high', ARRAY['growth', 'subscriptions', 'monetization'], true),

  ('Facebook', 'Product Manager', 'behavioral', 'Design a feature to combat misinformation', 'Approach: 1) Define misinformation types, 2) Understand spread patterns, 3) Solutions (fact-checking labels, source credibility, viral content review, user reporting, reduce distribution), 4) Balance free expression, 5) Test and iterate, 6) Metrics (misinformation prevalence, user trust, engagement impact). Show nuance.', ARRAY['Define the problem clearly', 'Multi-layered approach', 'Acknowledge trade-offs', 'Consider unintended consequences', 'Measure effectively'], 'hard', 'very_high', ARRAY['trust-safety', 'product-design', 'policy'], true),

  ('Stripe', 'Product Manager', 'behavioral', 'How would you expand Stripe to a new country?', 'Framework: 1) Market research (payment methods, regulations, competition), 2) Local requirements (compliance, currencies, local partnerships), 3) Go-to-market (customer segments, pricing), 4) Product adaptation (local payment methods, language), 5) Partnerships (banks, local processors), 6) Success metrics (merchant signups, TPV, market share).', ARRAY['Research local market deeply', 'Understand regulatory environment', 'Identify local payment preferences', 'Build partnerships', 'Phased rollout approach'], 'hard', 'high', ARRAY['international', 'go-to-market', 'fintech'], false),

  ('Twitter', 'Product Manager', 'behavioral', 'How would you make Twitter more welcoming for new users?', 'Process: 1) Understand new user experience (onboarding, initial follows, content quality), 2) Identify drop-off points, 3) Solutions (improved onboarding, interest-based recommendations, quality filters, tutorials, community guidelines prominence), 4) Test with new user cohorts, 5) Metrics (activation rate, D7/D30 retention, engagement).', ARRAY['Map new user journey', 'Identify friction points', 'Improve onboarding flow', 'Surface quality content', 'Measure activation'], 'hard', 'high', ARRAY['onboarding', 'user-experience', 'growth'], false),

  ('Google', 'Product Manager', 'behavioral', 'Estimate the market size for Google Workspace', 'Framework (TAM/SAM/SOM): 1) Total businesses globally, 2) Segment by size (SMB, mid-market, enterprise), 3) Seats per company, 4) Pricing per seat, 5) Penetration rates, 6) Calculate TAM/SAM/SOM. Consider remote work trends, competition. Show structured thinking.', ARRAY['Use TAM/SAM/SOM framework', 'Segment market clearly', 'State all assumptions', 'Sanity check numbers', 'Consider growth trends'], 'medium', 'high', ARRAY['market-sizing', 'estimation'], false),

  ('Uber', 'Product Manager', 'behavioral', 'Tell me about a time you used data to drive a product decision', 'STAR: Describe decision faced. Explain data gathered (quantitative and qualitative), analysis performed, insights discovered, how data informed decision, and outcome. Show data literacy and analytical rigor.', ARRAY['Show data analysis skills', 'Combine quant and qual data', 'Explain insights clearly', 'Connect data to decision', 'Quantify impact'], 'medium', 'high', ARRAY['data-driven', 'analytics', 'decision-making'], false),

  ('Airbnb', 'Product Manager', 'behavioral', 'How would you improve the host experience on Airbnb?', 'Framework: 1) Understand host journey (onboarding, listing creation, bookings, guest management, payouts), 2) Segment hosts (new vs experienced, casual vs professional), 3) Pain points (pricing, calendar management, guest communication, trust/safety), 4) Solutions (dynamic pricing, automation, better tools, support, education), 5) Metrics (host satisfaction, listings quality, host retention).', ARRAY['Map host journey', 'Segment host types', 'Research pain points', 'Propose tools and automation', 'Measure host success'], 'hard', 'high', ARRAY['marketplace', 'supply-side', 'user-experience'], false),

  ('Meta', 'Product Manager', 'behavioral', 'Should Facebook build a dating feature? (Hindsight: Facebook Dating)', 'Framework: 1) Market opportunity (single users, competition from Tinder/Bumble), 2) User demand and fit, 3) Competitive advantage (social graph, verification), 4) Risks (privacy concerns, impact on core product), 5) Financials (monetization, investment), 6) Recommendation with mitigation plan.', ARRAY['Assess market opportunity', 'Leverage unique assets', 'Address privacy concerns', 'Analyze competition', 'Consider brand impact'], 'hard', 'very_high', ARRAY['strategy', 'new-product', 'dating'], true),

  ('Spotify', 'Product Manager', 'behavioral', 'How would you improve Spotify for artists?', 'Process: 1) Understand artist needs (discovery, revenue, engagement with fans), 2) Segment artists (emerging vs established), 3) Pain points (discoverability, analytics, monetization), 4) Solutions (Spotify for Artists improvements, direct fan engagement, better analytics, merchandising integration), 5) Metrics (artist satisfaction, uploads, artist retention, creator diversity).', ARRAY['Research artist needs', 'Segment artist types', 'Balance with listener experience', 'Improve tools and analytics', 'Measure artist success'], 'hard', 'high', ARRAY['creator-economy', 'marketplace', 'music'], false);

-- CONSULTANT - Additional questions (20+ more)

INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('McKinsey', 'Consultant', 'case_study', 'A hotel chain wants to improve profitability. What do you recommend?', 'Framework: 1) Clarify (geography, hotel types, current margins), 2) Profit tree (Revenue: rooms, F&B, events; Costs: labor, property, utilities), 3) Benchmark industry, 4) Deep-dive high-impact areas (occupancy rates, ADR, RevPAR, cost per occupied room), 5) Solutions (dynamic pricing, F&B optimization, cost management, loyalty program), 6) Implementation roadmap.', ARRAY['Use profitability framework', 'Calculate RevPAR', 'Benchmark competitors', 'Prioritize by impact', 'Consider implementation'], 'hard', 'very_high', ARRAY['profitability', 'hospitality', 'pricing'], true),

  ('BCG', 'Consultant', 'case_study', 'Should a bank launch a mobile-only digital bank?', 'Framework: 1) Market attractiveness (digital banking growth, demographics, competition), 2) Customer needs (convenience, fees, features), 3) Bank capabilities (tech, brand, capital), 4) Business case (customer acquisition cost, deposits, revenue, profitability timeline), 5) Risks (cannibalization, regulation, competition), 6) Recommendation.', ARRAY['Assess digital banking trend', 'Analyze competitive landscape', 'Build financial model', 'Address cannibalization', 'Consider regulatory'], 'hard', 'very_high', ARRAY['digital-transformation', 'banking', 'strategy'], true),

  ('Bain', 'Consultant', 'case_study', 'A grocery chain is losing market share. Why and what should they do?', 'Framework: 1) Clarify market definition and timeframe, 2) Diagnose (pricing, assortment, store experience, location, online), 3) Competitive analysis, 4) Customer research, 5) Solutions (pricing strategy, assortment optimization, store refresh, omnichannel, loyalty), 6) Quantify impact, prioritize.', ARRAY['Diagnose competitive position', 'Analyze price vs value', 'Consider omnichannel', 'Deep-dive customer preferences', 'Prioritize initiatives'], 'hard', 'very_high', ARRAY['competitive-strategy', 'retail', 'market-share'], true),

  ('Deloitte', 'Consultant', 'behavioral', 'Tell me about a time you had to analyze data to solve a problem', 'STAR: Complex business problem requiring data analysis. Explain data sources, analysis techniques (segmentation, regression, trends), insights discovered, recommendation made, and business impact. Show analytical rigor.', ARRAY['Describe data sources', 'Explain analysis approach', 'Show insight generation', 'Connect to business impact', 'Quantify outcome'], 'medium', 'high', ARRAY['analytics', 'problem-solving'], false),

  ('McKinsey', 'Consultant', 'case_study', 'Estimate the market for electric vehicles in the US in 2030', 'Framework: 1) Total vehicle market (annual sales ~17M), 2) EV penetration assumption (30-50% by 2030), 3) ASP for EVs ($45k), 4) Calculate market size, 5) Segment by vehicle type, 6) Sanity check with growth rates. Show structured thinking.', ARRAY['Bottom-up approach', 'State assumptions clearly', 'Use current trends', 'Segment the market', 'Sanity check answer'], 'medium', 'high', ARRAY['market-sizing', 'automotive', 'estimation'], false),

  ('BCG', 'Consultant', 'behavioral', 'Describe a time you had to present to senior executives', 'STAR: High-stakes presentation. Explain preparation (exec summary, anticipating questions, practicing), tailoring message to audience, handling questions, and outcome. Show communication skills and executive presence.', ARRAY['Tailor to audience', 'Lead with recommendation', 'Use structured communication', 'Handle questions well', 'Show confidence'], 'medium', 'high', ARRAY['communication', 'executive-presence'], false),

  ('Oliver Wyman', 'Consultant', 'case_study', 'An airline wants to reduce fuel costs by 15%. How?', 'Framework: 1) Understand fuel cost components (price, efficiency, routes), 2) Price hedging strategies, 3) Operational efficiency (aircraft type, weight reduction, flight planning, speed optimization), 4) Fleet modernization, 5) Quantify each lever, 6) Achieve 15% through combination, discuss trade-offs.', ARRAY['Break down cost structure', 'Consider multiple levers', 'Quantify each opportunity', 'Discuss trade-offs', 'Realistic 15% target'], 'hard', 'high', ARRAY['cost-reduction', 'aviation', 'operations'], false),

  ('Accenture', 'Consultant', 'behavioral', 'How do you manage multiple client projects simultaneously?', 'Describe approach: 1) Prioritization framework, 2) Time blocking, 3) Stakeholder communication, 4) Delegation, 5) Tools/systems, 6) Escalation when needed. Give specific example of juggling projects successfully.', ARRAY['Show prioritization skills', 'Demonstrate organization', 'Emphasize communication', 'Discuss delegation', 'Provide concrete example'], 'medium', 'high', ARRAY['project-management', 'prioritization'], false),

  ('PwC', 'Consultant', 'case_study', 'A consumer goods company wants to expand its product portfolio. How should they decide what products to add?', 'Framework: 1) Strategic objectives (growth, margins, market share), 2) Market analysis (white spaces, growth segments, competitive intensity), 3) Capabilities assessment (brand, distribution, operations), 4) Portfolio analysis (adjacencies vs new categories), 5) Financial evaluation (investment, margins, payback), 6) Recommendation with risk assessment.', ARRAY['Align with strategy', 'Identify white spaces', 'Assess capabilities', 'Evaluate adjacencies', 'Build financial model'], 'hard', 'very_high', ARRAY['growth-strategy', 'portfolio', 'CPG'], true),

  ('EY', 'Consultant', 'behavioral', 'Tell me about a time you had to work under tight deadlines', 'STAR: Project with compressed timeline. Explain how you managed time, prioritized tasks, coordinated team, maintained quality, and delivered on time. Show resilience and time management.', ARRAY['Show time management', 'Demonstrate prioritization', 'Emphasize team coordination', 'Maintain quality focus', 'Quantify outcome'], 'medium', 'high', ARRAY['time-management', 'resilience'], false),

  ('Kearney', 'Consultant', 'case_study', 'A manufacturing company wants to reduce its carbon footprint. How would you approach this?', 'Framework: 1) Baseline current emissions (Scope 1, 2, 3), 2) Set target (science-based), 3) Reduction opportunities (energy efficiency, renewable energy, process optimization, supply chain, offsets), 4) Cost-benefit analysis, 5) Roadmap with milestones, 6) Implementation challenges.', ARRAY['Understand emission sources', 'Set clear targets', 'Prioritize reduction levers', 'Build business case', 'Address implementation'], 'hard', 'high', ARRAY['sustainability', 'operations', 'ESG'], false),

  ('Roland Berger', 'Consultant', 'behavioral', 'How do you handle disagreement with a team member or manager?', 'Describe approach: 1) Active listening, 2) Understanding their perspective, 3) Data-driven discussion, 4) Finding common ground, 5) Escalation if needed, 6) Maintaining relationship. Give specific example.', ARRAY['Show emotional intelligence', 'Use data to resolve', 'Demonstrate respect', 'Focus on outcome', 'Maintain relationships'], 'medium', 'high', ARRAY['conflict-resolution', 'teamwork'], false),

  ('Deloitte', 'Consultant', 'case_study', 'How many coffee shops should Starbucks open in Tokyo?', 'Framework (Market Sizing): 1) Tokyo population (14M), 2) Coffee shop visit frequency (2x/week), 3) Visits per year, 4) Starbucks market share target (15%), 5) Customers per store per year, 6) Calculate: (14M * 2 * 52 * 15%) / (customers per store). Sanity check with geography.', ARRAY['Use structured approach', 'State all assumptions', 'Consider market share', 'Account for capacity', 'Geographic sanity check'], 'medium', 'high', ARRAY['market-sizing', 'retail', 'estimation'], false),

  ('BCG', 'Consultant', 'case_study', 'A tech company is deciding between building or acquiring a new capability. How should they decide?', 'Framework: 1) Strategic importance and urgency, 2) Build analysis (time, cost, capability, risk), 3) Acquire analysis (targets, valuation, integration), 4) Partnership option, 5) Financial comparison (NPV, IRR), 6) Recommendation based on strategic fit, speed, and economics.', ARRAY['Assess strategic importance', 'Analyze build vs buy trade-offs', 'Consider time to market', 'Financial comparison', 'Address integration risks'], 'hard', 'very_high', ARRAY['M&A', 'build-vs-buy', 'strategy'], true),

  ('McKinsey', 'Consultant', 'behavioral', 'Tell me about your greatest professional achievement', 'Structure: 1) Context and challenge, 2) Your specific role and actions, 3) Obstacles overcome, 4) Quantifiable impact, 5) What made it meaningful to you. Choose achievement showing impact, leadership, and problem-solving.', ARRAY['Show quantifiable impact', 'Emphasize your specific contribution', 'Demonstrate leadership', 'Show problem-solving', 'Be authentic'], 'medium', 'high', ARRAY['achievements', 'impact'], false),

  ('Bain', 'Consultant', 'case_study', 'A private equity firm is considering buying a software company. What should they evaluate?', 'Framework (PE lens): 1) Market (TAM, growth, competitive dynamics), 2) Company assessment (revenue model, growth, margins, customer concentration, churn), 3) Value creation plan (growth initiatives, operational improvements, M&A), 4) Exit strategy and multiples, 5) Returns analysis (IRR, MoM), 6) Key risks.', ARRAY['Use PE framework', 'Focus on value creation', 'Analyze unit economics', 'Model returns', 'Identify key risks'], 'hard', 'very_high', ARRAY['private-equity', 'due-diligence', 'software'], true),

  ('Accenture', 'Consultant', 'behavioral', 'Why consulting? Why Accenture?', '1) Why consulting: Problem-solving, learning, variety of industries, client impact, fast career growth. 2) Why Accenture: Technology focus, scale and global reach, digital transformation leadership, specific practice areas (cloud, analytics), culture. Be specific and genuine.', ARRAY['Show genuine interest', 'Reference specific Accenture work', 'Mention practice areas', 'Discuss technology focus', 'Be authentic'], 'medium', 'high', ARRAY['motivation', 'firm-culture'], false);

-- INVESTMENT BANKING - Additional questions (20+ more)

INSERT INTO interview_questions (company, role, type, question, answer, tips, difficulty, priority, tags, is_featured) VALUES
  ('Goldman Sachs', 'Investment Banking Analyst', 'technical', 'Walk me through a merger model', 'Merger model: 1) Project standalone financials for acquirer and target, 2) Determine purchase price and consideration (cash, stock, or mix), 3) Calculate goodwill and purchase accounting adjustments, 4) Combine balance sheets and income statements, 5) Calculate pro forma EPS, 6) Perform accretion/dilution analysis. Show if deal is accretive or dilutive to acquirer EPS.', ARRAY['Understand purchase accounting', 'Calculate goodwill correctly', 'Model pro forma financials', 'Analyze accretion/dilution', 'Consider synergies'], 'hard', 'very_high', ARRAY['M&A', 'financial-modeling', 'accounting'], true),

  ('J.P. Morgan', 'Investment Banking Analyst', 'technical', 'What drives enterprise value?', 'EV drivers: 1) Cash flow generation (higher FCF = higher EV), 2) Growth rate (higher growth = higher multiple), 3) Risk/WACC (lower risk = higher value), 4) Profitability margins (higher margins = more valuable), 5) Asset efficiency (capital intensity), 6) Competitive position. Explain through DCF lens.', ARRAY['Connect to DCF', 'Discuss cash flow importance', 'Explain growth vs risk trade-off', 'Mention ROIC vs WACC', 'Show holistic understanding'], 'medium', 'very_high', ARRAY['valuation', 'corporate-finance'], true),

  ('Morgan Stanley', 'Investment Banking Analyst', 'behavioral', 'Why investment banking? Why Morgan Stanley?', '1) Why IB: Passion for finance, steep learning curve, exposure to M&A/capital markets, working with senior executives, foundation for career. 2) Why MS: Culture, deal flow, specific industry groups, training program, people you''ve met. Be specific and genuine.', ARRAY['Show genuine passion for finance', 'Reference specific deals/groups', 'Mention people you met', 'Discuss culture fit', 'Be authentic'], 'medium', 'very_high', ARRAY['motivation', 'firm-culture'], true),

  ('Bank of America', 'Investment Banking Analyst', 'technical', 'Explain the difference between diluted and basic EPS', 'Basic EPS = Net Income / Weighted Average Shares Outstanding. Diluted EPS includes potential dilution from stock options, convertibles, warrants using treasury stock method or if-converted method. Diluted EPS is always ≤ Basic EPS. Anti-dilutive securities excluded from diluted calculation.', ARRAY['Define both clearly', 'Explain treasury stock method', 'Discuss if-converted method', 'Mention anti-dilution', 'Know when to use which'], 'medium', 'high', ARRAY['accounting', 'equity'], false),

  ('Citi', 'Investment Banking Analyst', 'technical', 'What happens to enterprise value in an LBO?', 'Enterprise value doesn''t change in an LBO (same operating business). Only capital structure changes. Pre-LBO: EV = Equity + Debt. Post-LBO: Same EV, but more Debt, less Equity. Equity value decreases as leverage increases, but EV constant.', ARRAY['Explain EV stays constant', 'Show capital structure change', 'Walk through example', 'Discuss leverage impact', 'Mention equity bridge'], 'medium', 'very_high', ARRAY['LBO', 'valuation', 'leverage'], true),

  ('Deutsche Bank', 'Investment Banking Analyst', 'behavioral', 'Tell me about a time you worked on a team project', 'STAR: Describe team project with clear roles. Explain your contribution, how team collaborated, challenges faced, how conflicts resolved, and successful outcome. Show teamwork and leadership.', ARRAY['Emphasize collaboration', 'Show your specific value-add', 'Discuss conflict resolution', 'Demonstrate leadership', 'Quantify outcome'], 'medium', 'high', ARRAY['teamwork', 'collaboration'], false),

  ('Barclays', 'Investment Banking Analyst', 'technical', 'How would you value a company with negative earnings?', 'Methods: 1) Revenue multiples (EV/Revenue) if no positive EBITDA, 2) DCF to terminal value (use when profitable), 3) Precedent transactions, 4) Comparable companies (adjust for loss-making), 5) Asset-based valuation if asset-heavy. Discuss assumptions and uncertainties.', ARRAY['Use revenue multiples', 'Explain challenges', 'Consider growth trajectory', 'Discuss terminal value carefully', 'Acknowledge higher uncertainty'], 'hard', 'very_high', ARRAY['valuation', 'startups'], true),

  ('UBS', 'Investment Banking Analyst', 'technical', 'Walk me through how to calculate free cash flow', 'Unlevered FCF: Start with EBIT, subtract taxes (EBIT × (1-tax rate)) = NOPAT, add back D&A (non-cash), subtract Change in NWC, subtract CapEx. Formula: NOPAT + D&A - ΔNW - CapEx. Levered FCF: Start with Net Income instead.', ARRAY['Know both levered and unlevered', 'Explain each component', 'Walk through example', 'Discuss NWC changes', 'Mention use in DCF'], 'medium', 'very_high', ARRAY['financial-statements', 'valuation'], true),

  ('Jefferies', 'Investment Banking Analyst', 'behavioral', 'Describe a time you had to learn something complex quickly', 'STAR: New technical concept or industry. Explain urgency, learning approach (reading, courses, asking experts), application to work, and outcome. Show learning agility.', ARRAY['Show resourcefulness', 'Demonstrate structured learning', 'Emphasize quick application', 'Quantify timeline', 'Show impact'], 'medium', 'high', ARRAY['learning-agility', 'adaptability'], false),

  ('Lazard', 'Investment Banking Analyst', 'technical', 'How do you calculate beta?', 'Beta = Covariance(Stock Returns, Market Returns) / Variance(Market Returns). Or run regression of stock returns vs market returns, slope = beta. Beta > 1 = more volatile than market. Beta < 1 = less volatile. Beta measures systematic risk.', ARRAY['Know formula', 'Explain regression approach', 'Interpret beta values', 'Discuss systematic risk', 'Mention use in CAPM'], 'medium', 'high', ARRAY['finance', 'CAPM', 'risk'], false),

  ('Credit Suisse', 'Investment Banking Analyst', 'technical', 'Why do we add back D&A in cash flow statement?', 'D&A is a non-cash expense. It reduced Net Income on IS, but no cash actually left the company. In Cash Flow Statement (indirect method), we start with Net Income and add back D&A to get to actual cash generated from operations.', ARRAY['Explain non-cash nature', 'Walk through IS to CF', 'Discuss indirect method', 'Mention tax shield separately', 'Show clear understanding'], 'easy', 'very_high', ARRAY['accounting', 'cash-flow'], true),

  ('Goldman Sachs', 'Investment Banking Analyst', 'technical', 'What is goodwill and how is it created?', 'Goodwill = Purchase Price - Fair Value of Net Assets Acquired. Created in M&A when acquirer pays premium over book value. Represents intangibles like brand, customer relationships, synergies. Not amortized (IFRS/GAAP), but tested annually for impairment.', ARRAY['Know formula', 'Explain M&A context', 'Discuss intangible value', 'Mention impairment testing', 'Understand accounting treatment'], 'medium', 'very_high', ARRAY['M&A', 'accounting', 'goodwill'], true),

  ('Morgan Stanley', 'Investment Banking Analyst', 'behavioral', 'Tell me about a time you made a mistake', 'STAR: Specific mistake in analysis or work product. Explain what happened, how you caught it (or it was caught), how you fixed it, communication with team, and lessons learned. Show accountability and growth.', ARRAY['Take full ownership', 'Show how you fixed it', 'Emphasize lessons learned', 'Demonstrate attention to detail now', 'Keep professional'], 'medium', 'high', ARRAY['accountability', 'learning'], false),

  ('J.P. Morgan', 'Investment Banking Analyst', 'technical', 'Walk me through calculating working capital', 'Working Capital = Current Assets - Current Liabilities. Operating Working Capital (more common in valuation) = (Accounts Receivable + Inventory) - Accounts Payable. Change in WC = WC_current - WC_prior. Increase in WC uses cash, decrease in WC generates cash.', ARRAY['Know both definitions', 'Explain operating WC', 'Discuss change in WC', 'Connect to cash flow', 'Walk through example'], 'medium', 'high', ARRAY['accounting', 'working-capital'], false),

  ('Bank of America', 'Investment Banking Analyst', 'technical', 'How would you value a bank?', 'Banks valued differently: 1) P/E multiple (not EV/EBITDA as debt is asset), 2) Price/Book or Price/Tangible Book, 3) Dividend Discount Model, 4) Sum-of-the-parts for divisions. Discuss why EV/EBITDA not used (debt is inventory for banks).', ARRAY['Explain unique bank valuation', 'Use P/E and P/B multiples', 'Discuss DDM', 'Explain why not EV/EBITDA', 'Consider asset quality'], 'hard', 'very_high', ARRAY['valuation', 'banking', 'financials'], true),

  ('Barclays', 'Investment Banking Analyst', 'technical', 'What is EBITDA and why is it used?', 'EBITDA = Earnings Before Interest, Taxes, Depreciation, Amortization. Used because: 1) Proxy for cash flow, 2) Removes financing and accounting policy differences, 3) Allows operational comparison, 4) Common in EV multiples. Limitations: Ignores CapEx, WC changes, not true cash flow.', ARRAY['Know formula', 'Explain why it''s used', 'Discuss limitations', 'Compare to cash flow', 'Mention use in multiples'], 'easy', 'very_high', ARRAY['accounting', 'valuation'], true),

  ('Citi', 'Investment Banking Analyst', 'behavioral', 'How do you prioritize your work?', 'Framework: 1) Urgency and importance matrix, 2) Communicate with seniors on priorities, 3) Break down large tasks, 4) Time blocking, 5) Regular check-ins. Give example of managing multiple live deals.', ARRAY['Show framework', 'Emphasize communication', 'Demonstrate organization', 'Give banking-specific example', 'Show you can handle pressure'], 'medium', 'high', ARRAY['prioritization', 'organization'], false),

  ('UBS', 'Investment Banking Analyst', 'technical', 'Explain the concept of terminal value', 'Terminal Value = Value of company beyond forecast period in DCF. Two methods: 1) Perpetuity Growth: TV = FCF_final × (1+g) / (WACC-g), 2) Exit Multiple: TV = EBITDA_final × Multiple. TV typically 60-80% of total value. Assumes steady-state growth forever.', ARRAY['Know both methods', 'Explain perpetuity growth formula', 'Discuss exit multiple approach', 'Mention typical % of value', 'Show when to use each'], 'medium', 'very_high', ARRAY['valuation', 'DCF', 'terminal-value'], true),

  ('Goldman Sachs', 'Investment Banking Analyst', 'technical', 'What causes a company''s stock price to increase?', 'Stock price driven by: 1) Earnings growth (higher NI), 2) Multiple expansion (higher P/E due to growth prospects, lower risk), 3) Market sentiment, 4) Industry trends, 5) Company-specific catalysts (new product, M&A). Fundamentally: future cash flows and risk.', ARRAY['Discuss earnings and multiples', 'Explain growth vs risk', 'Mention catalysts', 'Connect to DCF logic', 'Show market understanding'], 'medium', 'high', ARRAY['equity-markets', 'valuation'], false);
